config/routes.rb
PoemToday::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", sessions: "sessions" }

  devise_scope :user do
    authenticated :user do
      root 'user_poems#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end 

  resources :user_poems, only: :index
  resources :poems, only: :show
  post 'poems/voice' => 'poems#voice'
  post 'poems/search' => 'poems#search'
  get  '/ephemeral' => 'poems#ephemeral'
  get  '/about' => 'welcome#index'
  

end

app/models/poems/occasion.rb
class Occasion < ActiveRecord::Base
    has_many :poem_occasions
    has_many :poems, :through => :poem_occasions
end

app/models/poems/poem.rb
class Poem < ActiveRecord::Base
  has_many :user_poems
  has_many :users, :through => :user_poems
  has_many :poem_subjects
  has_many :subjects, :through => :poem_subjects
  has_many :poem_occasions
  has_many :occasions, :through => :poem_occasions

  include PgSearch
  pg_search_scope :search_by_occasion,    :associated_against => {:occasions => :name},     :using => {:tsearch => {:dictionary => "english"}}
  pg_search_scope :search_by_subject,     :associated_against => {:subjects  => :name},     :using => {:tsearch => {:dictionary => "english"}}
  pg_search_scope :search_by_title,       :against => [:title],                             :using => {:tsearch => {:dictionary => "english"}}
  pg_search_scope :search_by_first_line,  :against => [:first_line],                        :using => {:tsearch => {:dictionary => "english"}}
  pg_search_scope :search_by_content,     :against => [:content],                           :using => {:tsearch => {:dictionary => "english"}}
  pg_search_scope :search_by_poet,        :against => [:poet],                              :using => {:tsearch => {:dictionary => "english"}}

end



    # book = GoogleBooks.search(self.isbn).first
    # book_image = book.image_link(:zoom => 2)

app/models/poems/poem_occasion.rb
class PoemOccasion < ActiveRecord::Base
    belongs_to :poem
    belongs_to :occasion
end

app/models/poems/poem_subject.rb
class PoemSubject < ActiveRecord::Base
  belongs_to :poem
  belongs_to :subject
end

app/models/poems/subject.rb
class Subject < ActiveRecord::Base
    has_many :poem_subjects
    has_many :poems, :through => :poem_subjects
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :voice
  after_filter :set_header, only: :voice
  include Webhookable

  def show
    @poem = Poem.find(params[:id])
    new_twilio_token

    if params[:keyword]
      @poem_keyword = params[:keyword] #from the daily email
    elsif session[:ephemeral_poem].present?
      @poem_keyword = session[:ephemeral_poem].values.last #from clicked_word
    elsif current_user && (current_user.created_at > DateTime.now.beginning_of_day)
      @poem_keyword = current_user.first_name
    else
      @poem_keyword = @poem.first_line.downcase.split.max_by(&:length).gsub(/’s|[^a-z\s]/,'')
    end

    @poem_image_url = image_url(@poem_keyword) 
  end

  def voice
    response = Twilio::TwiML::Response.new do |r|
      r.Say "#{params[:voice_title]}", :voice => 'man'
      r.Say "by #{params[:voice_poet]}"
      r.Say "#{params[:voice_content]}"
    end
    render_twiml response
  end

  def search
    clicked_word = params[:clicked_word].downcase.gsub(/’s|[^a-z\s]/,'')
    from_poem_id = params[:from_poem].to_i
    poem_kw = []
    poem_kw << Keyword.new(clicked_word,0,from_poem_id,:user)
    results = KeywordSearch.new(poem_kw).match_keywords_to_poems
    results.delete_if { |result| result[:poem_id] == from_poem_id }
    if results.empty?
      redirect_to Poem.find(from_poem_id), notice: "I don't know of any #{clicked_word} poems."
    else
      if session[:ephemeral_poem].nil?
        session[:ephemeral_poem] = {}
      end
      session[:ephemeral_poem][from_poem_id] = clicked_word
      if ephemeral_poem?
        redirect_to poem_path(results.first[:poem_id]), notice: %Q[You've created a new <a href="#{ephemeral_path}"> poem</a>.].html_safe
      else
        redirect_to poem_path(results.first[:poem_id])
      end
    end

  end

  def ephemeral
    if ephemeral_poem?
      markov = MarkyMarkov::TemporaryDictionary.new
      session[:ephemeral_poem].keys.each { |poem_id| markov.parse_string(Poem.find(poem_id).content) }
      @poem_title = session[:ephemeral_poem].values[-4..-1].join(' ')
      @poem_content = []
      3.times { @poem_content << markov.generate_1_sentences }
      @poem_keyword = @poem_content.first.downcase.split.max_by(&:length).gsub(/’s|[^a-z\s]/,'')
      @poem_image_url = image_url(@poem_keyword)
      markov.clear!
      session[:ephemeral_poem] = {}
      new_twilio_token
    else
      flash[:notice] = "This correlation is well established for ephemeral species."
      redirect_to authenticated_root_path
    end
  end

  def new_twilio_token
    capability = Twilio::Util::Capability.new(ENV["TWILIO_ACCOUNT_SID"],ENV["TWILIO_AUTH_TOKEN"])
    capability.allow_client_outgoing(ENV["TWILIO_APPLICATION_SID"])
    @token = capability.generate
  end

end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/_poem_image.html.erb
<div>
  <% if !@poem_image_url.nil? %>
    <%= image_tag @poem_image_url %>
    <p><%= @poem_keyword %></p>
  <% end %>
</div>

app/views/poems/ephemeral.html.erb
<div id="poem-image">
    <%= render 'poem_image' %>
</div>

<div class="col-md-5 col-md-offset-1">
  <h2 id="poem-title"><%= @poem_title %></h2>
  <%= content_tag "div", id: "token", data: {token: @token } do %><% end %>
  <%= hidden_field_tag "title", "#{@poem_title}", id: "voice-title" %>
  <%= hidden_field_tag "poet", "#{@poem_poet}", id: "voice-poet" %>
  <%= hidden_field_tag "content", "#{@poem_content}", id: "voice-content" %>
  <h5 id="poem-poet">a marhov chain</h5><br>

  <p id="poem-body"><% @poem_content.each do |line| %>
    <% line.split.each do |word| %>
      <%= link_to word, poems_search_path(clicked_word:word, from_poem:1), method: :post, class: "poem-word" %><% end %><br><% end %>
  </p>
</div>

app/views/poems/show.html.erb
<div id="poem-image">
    <%= render 'poem_image' %>
</div>

<div class="col-md-5 col-md-offset-1 poem">
  <h2 id="poem-title"><%= @poem.title %></h2><%= button_tag fa_icon("volume-up lg"), id: "keillorbot" %>
  <%= content_tag "div", id: "token", data: {token: @token } do %><% end %>
  <%= hidden_field_tag "title", "#{@poem.title}", id: "voice-title" %>
  <%= hidden_field_tag "poet", "#{@poem.poet}", id: "voice-poet" %>
  <%= hidden_field_tag "content", "#{@poem.content}", id: "voice-content" %>
  <h5 id="poem-poet">BY <%= @poem.poet.upcase %></h5><br>

  <p id="poem-body"><% @poem.content.split("\n").each do |line| %>
      <% line.split.each do |word| %>
        <%= link_to word, poems_search_path(clicked_word:word, from_poem:@poem.id), method: :post, class: "poem-word" %><% end %><br><% end %>
  </p>
</div>
  