config/routes.rb
PoemToday::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", sessions: "sessions" }

  devise_scope :user do
    authenticated :user do
      root 'user_poems#index', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/registrations#new', as: :unauthenticated_root
    end
  end 

  resources :user_poems, only: :index
  resources :poems, only: :show
  post 'poems/voice' => 'poems#voice'
  post 'poems/search' => 'poems#search'
  get  '/ephemeral' => 'poems#ephemeral'
  get  '/about' => 'welcome#index'
  

end

app/views/layouts/_footer.html.erb
<div class="push"></div></div>
<div class="footer">made by <%= link_to "alex patriquin", "https://twitter.com/apatriq" %> at the flatiron school.</div>

app/views/layouts/_logo.html.erb
  <%= link_to (image_tag 'icon_31093.png', size: "35", id: 'logo-png'), authenticated_root_path %>
  <h1 id="brand"><%= link_to "PoemToday", authenticated_root_path %></h1>

app/views/layouts/_navigation.html.erb
<div>
  <%= render 'layouts/logo' %>
  <%= render 'layouts/signin_nav_links' %>
</div>

app/views/layouts/_notices.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> pt-alert-container">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul class="pt-alert">
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/_signin_nav_links.html.erb
<div id="signin_nav_links">
    <%= link_to 'About', about_path %> |
  <% if user_signed_in? %>
    <%= link_to 'Edit profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoemToday</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "//static.twilio.com/libs/twiliojs/1.1/twilio.min.js" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'icon_31093.png' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Cardo:400,400italic,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
  <div id="redstripe"></div>
  <br>
  <div class="container-fluid wrapper">
    <%= render 'layouts/navigation' %>
    <div class="row notice-spacer">
      <%= render 'layouts/notices' %>
    </div>
    <div class="row">
      <%= yield %>
    </div>  
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>